(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0)","#000000"],[0.529,1],-17.7,-10,0,-17.7,-10,73.2).s().p("AAfH0IgjAAIgBAAIgUAAIAAgBIgCAAIgFAAIgCAAQgHAAgEgCIgBAAIgBgBIgBAAIgBAAIgBAAQgMAAgHgDIgCAAIgDAAIgBgBQgGABgFgDIgBAAQgKAAgGgCIgBAAIgBAAIgBAAQgGgBgFgDIgBAAIgBgBIgCAAQgLgBgHgEIgCAAIgPgGIgBAAQgIgBgFgDIgBgBQgDAAgCgCQgLgCgIgEQhWglg/g9Qg/g8gphTQgphTgKhyIAAgBIAAgsIAAgBIAAgMIABAAIAAgBIAAgLQAOhvAthPQArhQBCg5QBCg6BZgiQBCgYBSgHIAxAAIABAAQAHADAKgCIACAAIALABIAAABQBsAPBOAsQBQAtA5BCQA6BCAhBZQAMAfAIAiQAHAcADAfIABACIABAZIAAABIABAAIAAANIAAACIAAAPIAAACIAAAVIAAACIgBAAQgDAugJAnQgaBig1BHQgDAIgEAFQg3BGhKAwQhLAwhmAWIgBAAIg+AIIAAABIgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-50,-50,100,100), null);


(lib.sun = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFF00","rgba(255,255,0,0)"],[0.596,0.945],0,0,0,0,0,5.6).s().p("AgkAlQgPgQABgVQgBgUAPgQQAQgPAUABQAVgBAQAPQAPAQgBAUQABAVgPAQQgQAPgVgBQgUABgQgPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// glow
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,0,0,0,0,9).s().p("Ag6A6QgYgYAAgiQAAghAYgZQAZgYAhAAQAiAAAYAYQAZAZAAAhQAAAigZAYQgYAZgiAAQghAAgZgZg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,0,0,0,0,1.3).s().p("AhHAJQgegEABgFQgBgEAegDQAegEApAAQAqAAAeAEQAdADAAAEQAAAFgdAEQgeADgqAAQgpAAgegDg");
	this.shape_2.setTransform(0.2,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,0,0,0,0,1.3).s().p("AgIBIQgDgeAAgqQAAgpADgeQAEgeAEAAQAFAAADAeQAEAeAAApQAAAqgEAeQgDAdgFABQgEgBgEgdg");
	this.shape_3.setTransform(0.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,1.5,0,0,1.5,1.3).s().p("AgKAzIgBgkQAAglADgcIARAAQADAcAAAlIgBAkg");
	this.shape_4.setTransform(0.2,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sun, new cjs.Rectangle(-10,-10,20.3,20.3), null);


(lib.juno_animated = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#996666").ss(1,1,1,3,true).p("AACihIAGATIAGAUIAFATIAGATIBYgmAhQhpIgGgTIBYglIBZglIAFATIAGATIAGATIAFATIAGATIAGATIhZAmIAGATIAFATIAGASIAGATIAFATIAGATIAGATIAFATIAGATIAAABIhYAlIAAgBIgGgTIgFgTIgGgTIgGgTIgFgTIgGgTIgGgTIgFgTIgGgSIgFgTIgGgTIgGgTIBYglIBZgmAhKhVIgGgUIBYglIBYglAijgwIgBgEQgDgIgCgHIBZgmAidgdQgCgGgCgFIAAgCIgCgGIBZglIBYglIBYgmAiSAIIgEgNIgCgFIgFgTIBYglIgFgTAiMAcIgGgUIBZgkIBYglIAFATIhYAlgAiYgKIBZglIBYglIAGATIBYgmAiBBBQgCgGgCgFIgCgIIBZglIBYgkIBYgmIAGAUIAGASIAFATIAGASIAFATIhYAmIhYAlIhZAmQgBgGgCgGIgCgHIgGgUIgFgSgAhlCgIgGgSAhaDGIgFgSIgGgUAgBCiIhZAlIAAgBAgdBCIhZAlAh7BVIBYgmIBYglIBZglAgMB7IhZAlAgHCOIhYAmAgYBVIhYAmAgBChIhZAlAiphDIgFgTIBYgmAgpAcIhYAlAiHAuIgFgSACIgtIhZAlIhYAkACTgIIhYAlIhYAlAB9hUIAFATACkAwIAGAUIAFASIAAABIhYAmACvBWIhYAmIhYAlACkAwIhYAmIhYAlACqBEIhZAlIhYAlACZAKIhZAmIhYAlACeAdIAGAT");
	this.shape.setTransform(37.7,-28.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666699").s().p("AAUBFIAGASIAGATIAFATIAAABgAgBgHIAFATIAFATIAGATIACAHgAgWhNIAEANIAGATIAFATIACAIgAgkh9IABAFIACAFg");
	this.shape_1.setTransform(24.9,-21.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#669999").s().p("AhaDGIBZglIAAAAIhZAmgAhfCzIBYglIhYAlIgGgTIBZglIhZAlIgGgSIBZgmIhZAmIgDgMIgCgHIBYgmIBYglIAGATIAGATIAFATIAGATIhYAlIBYglIAAAAIhYAlIAAAAIgGgTIBYglIhYAlIgFgTIBYglIhYAlIgGgTIBYglIhYAlIgGgTIAGATIAGATIAFATIAGATIhZAlgAgBChgAgHCOgABXB8IBYglIAAAAIhYAlgABXB8IgGgTIBZglIhZAlIgFgTIBYglIhYAlIgGgTIgGgTIBZgmIhZAmIgFgTIBYglIhYAlIAFATIhYAlIgFgTIBYglIhYAlIhZAmIgFgTIBYgmIhYAmIgGgUIBYglIBYgkIAGASIAGATIgGgTIBZglIAFATIAGASIAFATIhYAmIBYgmIAGAUIAGATIAFATIhYAlgAgdBCIgGgTIBYglIhYAlIgGgTIAGATgAhwB7IgGgTIBZgmIAFATIhYAmgABRBpgAgSBogACvBXgAgdBCgAiBBBIgEgLIgCgIIBZglIAFATIhYAlgAiMAbIBYgkIhYAkIgGgTIBZgkIAFATIAGASIhZAlgAgpAcIgFgTIBYgkIhYAkIgGgSIBYglIhYAlIgFgTIBYglIAFATIgFgTIBYglIhYAlIgGgTIBYglIhYAlIAGATIhYAlIgGgTIBYglIhYAlIhZAlIgFgSIBYgmIhYAmIgEgMIAAgCIgCgFIBZgmIAFATIAGATIgGgTIBYglIhYAlIgFgTIBYglIhYAlIgGgUIBYglIhYAlIAGAUIhZAmIgBgFIgFgPIBZgmIgGgTIAGATIhZAmIgFgTIBYgmIBYglIAGATIAGAUIAFATIAGATIgGgTIBZgmIhZAmIgFgTIBYgmIhYAmIgGgUIBYglIhYAlIgGgTIBZglIAFATIAGATIAGATIAFAUIAGATIAGATIhZAlIAGATIAFATIhYAkgAA1AKIgGgSIBZgmIhZAmIgFgTIBYglIhYAlIgGgTIBZglIAFATIAGASIAGATIhZAlgAguAJgAiSAIIgEgMIgCgGIBZglIAGATIhZAkgAAvgIgAg0gJgAAqgbgAg/gvgAAfhBgAAfhBgAAThngAhQhpgAAOh6gAAIiOg");
	this.shape_2.setTransform(37.7,-28.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#996666").ss(1,1,1,3,true).p("ABmigIAFATIAGATIAGATIAFATIhZAmIhXAlIgGgTIgFgTIgGgTIBXglIAGATIBZgmAhLhVIgFgTIgGgTIBYglIBZgmIAFATIAGATAACigIAFATIAGATIAFATIBZgmAAHiNIBZgmAhQhoIBXglAhLhVIBYglIBZgmAAehBIAFATIAGATIAGATIAFASIAGATIhYAlIgFgTIgGgTIgGgTIgFgSIhYAkIgBAAIgFgTIgGgSIgGgTIgFgTIgGgTIgFgTIBYglAgNB7IhYAlIgGgTIgGgTIgFgTIgGgTIgFgTIgGgTIgGgTAgSBoIgGgTIgGgTIhYAlIAAAAAgNB7IgFgTIhZAlAgCChIgFgTIgGgTAgBCiIgBgBIhYAlIAAAAIgGgTIgFgTABQBpIAGATIAAAAIhXAmIhZAlIAAgBAA/AwIAGATIAGATIAFATIhXAlIhYAlIgBAAAA/AwIhXAlIhYAlIgBAAAg6gcIBYglIBZgmAAvgIIhYAkIhYAlAgvAJIBYgkIBZgmIAGATIAFATIAGATIAFASIAGATIAGATIAFATIAGATIAAABIhZAlAgjAvIBXglIBZglABLBWIhYAlABWB8IhYAlABFBDIhXAlAA6AdIAFATAg/gvIBXglIAGATAhFhCIgGgTACvBWIhZAmACkAwIhZAmACpBDIhZAmACeAdIhZAmACYAKIhZAmACTgIIhZAlACIguIhZAmAB8hUIAGATAijgwIAAAAIBYglAiegdIABAAIBYglAiHAuIAAAAIBYglAiphDIBZglAiYgKIBZglAh8BUIBZglAiSAIIBYgk");
	this.shape_3.setTransform(10.3,-17.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#669999").s().p("AhaDGIAAAAIBYglIABABIhZAlgAhaDGIgGgTIABAAIBYglIhYAlIgBAAIgFgTIgGgTIBZglIhZAlIgGgTIABAAIBYglIhYAlIgBAAIgFgTIAAAAIBYglIAGATIAGATIAFATIhYAlIBYglIAGATIAFATIhYAlgAgCChIBYglIhYAlIgFgTIBXglIgFgTIBZgmIhZAmIgGgTIBZgmIhZAmIgGgTIBZgmIhZAmIgFgTIBZglIhZAlIAFATIhXAlIgGgTIBYglIgGgTIBZglIhZAlIgFgSIBZgmIhZAmIgGgTIBZgmIhZAmIgGgTIBZgmIAGATIAGATIAFATIAGATIAFASIAGATIAGATIAFATIAGATIAAABIhZAlIAAAAIBZgmIhZAmIgGgTIBZgmIhZAmIAGATIAAAAIhXAmgAgCChgAgHCOgAgHCOIgGgTIBYglIAFATIhXAlgABWB8gAgNB7IgFgTIBXglIAGATIhYAlgAgNB7gABQBpgAgSBoIgGgTIBXglIAGATIhXAlgAh2BnIgGgTIBZglIhZAlIgFgTIBYglIhYAlIgGgTIAAAAIBYglIAGATIAGATIAFATIhYAlgAgeBCgAgeBCgAgjAvIBXglIAGATIhYAlgAA/AwgAgjAvIgGgTIBYgkIAFASIhXAlgAiHAuIgGgTIABAAIBYgkIhYAkIgBAAIgFgTIBYgkIhYAkIgGgSIBZglIAFATIAGATIAFASIhYAlgAgpAcIgGgTIBYgkIAGATIhYAkgAiNAbgAgvAJIgFgSIBXglIAGATIhYAkgAg6gcIBYglIAFATIhXAlgAiYgKIgGgTIABAAIBYglIAGATIhZAlgAg6gcIgFgTIBXglIAGATIhYAlgAiegdIgFgTIAAAAIBYglIAGATIhYAlgAAehBIBZgmIhZAmIgGgTIBZgmIhZAmIhXAlIgGgTIBXglIAGATIgGgTIBZgmIhZAmIgFgTIBZgmIAFATIAGATIAGATIAFATIhZAmgAijgwIAAAAIgGgTIBZglIAFATIBYglIAFATIhXAlIgGgTIhYAlgAijgwgAAehBgAhFhCgAiuhWIBYglIBYglIAFATIhXAlIgGgTIAGATIhZAlgAhQhoIBXglIAGATIhYAlgAAShngAAShngAhQhogAANh6gAAHiNIBZgmIAGATIhZAmgAAHiNgAACigIBZgmIAFATIhZAmgABgizg");
	this.shape_4.setTransform(10.3,-17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#996666").ss(1,1,1,3,true).p("AhQhpIgFgTIBXglIAGATIAGAUIAFATIBZgmIAFATIAGATIAGATIAFATIAGATIAGATIAFATIAGASIhZAmIAGATIAGATIAFATIAGATIAAAAIhYAmIhZAlIAAgBIgFgTIgGgTIgGgSIgDgMIgCgIIgGgTIgFgTIgGgTIgEgLIgCgIIBZglIgFgSIgGgTIgGgTIgFgTIgGgTIBYglIBYgmIAGATAACihIBZglIAFATIAGATAAIiOIBYglAhQhpIBYglACTgIIhYAlIhYAlIgFgTIBXglIBZglAAvgIIhXAkIhZAlAAfhBIAFATIAGATIAFATIAGASIAGATIAFATIhXAlIgGgTIhZAlAAZhUIAGATIBYgmAgSBoIgFgTIhZAlAgMB7IgGgTIhZAmAgGCOIgGgTIhZAlABGBDIhYAlABRBpIhXAlIhZAlABMBWIhYAlAgiAvIgGgTIgGgTIBYgkIBYgmACIguIhZAmAB9hUIhZAmIhXAlIhZAlIgGgUIBZgkIBYglAidgdIgEgNIgCgGIgBgEIgFgPIgFgTIBZgmAiYgKIgFgTIBZglIBXglIAGATIBYgmAiSAIIgEgNIgCgFIBZglIBYglAiHAuIgFgSAijgwIBZglIgGgUAgBCiIAAgBIhZAlABXB8IhYAlIgFgTAh7BUIBZglAiphDIBZgmACkAwIAGAUIAFASIAAABIhYAlACeAdIAGATIhYAmACvBWIhYAmACqBEIhZAlACeAdIhYAmACZAKIAFAT");
	this.shape_5.setTransform(65.3,-40.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666699").s().p("AAUBEIAGAUIAGATIAFATIAAAAgAgBgHIAFASIAFATIAGATIACAIgAgWhOIAEAPIAGATIAFATIACAHgAgkh9IABAEIACAGg");
	this.shape_6.setTransform(52.5,-33);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#669999").s().p("AhaDHIBZgmIAAABIhZAlgAhfC0IBZgmIAFATIhZAmgAhfC0IgGgTIBZgmIhZAmIgGgUIBZglIhZAlIgDgLIgCgIIBZglIhZAlIgGgTIBZglIhZAlIgFgTIBZglIhZAlIgGgTIBZglIgGgTIAGATIhZAlIgEgLIgCgHIBZgmIgFgSIBXglIhXAlIgGgTIBYglIhYAlIgGgTIBYglIAGATIAFATIAGATIAFATIhXAkIAGATIAFATIAGATIAFATIAGATIBYglIAFATIAGATIhYAlIgFgTIBXglIhXAlIgGgTIAGATIhZAmgAguAJIBYgkgAgBChIBYglIAAABIAAgBIgGgTIBZgmIhZAmIgFgTIBYgmIhYAmIgGgTIBYgmIhYAmIgGgTIBZglIAFASIAGATIAGATIAFATIhYAmIBYgmIAAABIhYAmIhYAlgAgBChgAgSBoIBYglIAGATIhYAlgABRBpgAgSBoIgFgTIBXglIAGATIhYAlgACvBWgABMBWgAgXBVIgGgTIBYglIAFATIhXAlgAgdBCIgFgTIBXglIAGATIhYAlgABAAwIgFgTIBYgkIhYAkIgGgTIBZgkIAFATIAGASIhZAlgAgoAcIBXgkIAGASIhXAlgAiHAvIgFgTIBZglIAFASIhZAmgAiMAcIgGgTIBZglIhZAlIgEgOIgCgEIBZgmIAGATIAGATIhZAlgAAvgIIBZglIAGATIhZAkgAAvgIIgFgTIBYgmIAGAUIhZAlgAgzgJgAidgdIBZglIAFATIhZAmgACOgagAAqgbIgGgTIBZgmIAFATIhYAmgAg5gcgAidgdIgEgNIgCgGIBZglIhZAlIgBgEIgFgPIBZgmIAGAUIBYglIAFATIgFgTIBYglIAGASIAFATIAGATIhYAmIgGgTIBYgmIhYAmIhYAlIgFgTIBXglIAGATIgGgTIBZgmIhZAmIhXAlIgGgTIAGATIhZAlgAAkguIgFgTIBYgmIAGATIhZAmgAhEhCgAiuhWIBZglIAFASIhZAmgAB9hUgAAZhUgAhQhpIBYgkIAGATIhYAlgAhQhpIgFgSIBXglIAGATIhYAkgAAIiNIBYgmIhYAmIgGgTIBZgmIAFATIAGAUIhYAlgAhVh7gAAIiNg");
	this.shape_7.setTransform(65.3,-40.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#996666").ss(1,1,1).p("AB7AAQAABCgkAuQgkAugzAAQgyAAgjguQglguAAhCQAAhAAlguQAjgvAyAAQAzAAAkAvQAkAuAABAg");
	this.shape_8.setTransform(-23.2,-6.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#669999").s().p("AhVBvQgkguAAhBQAAhAAkguQAjgvAyABQAzgBAkAvQAjAuABBAQgBBBgjAuQgkAvgzAAQgyAAgjgvg");
	this.shape_9.setTransform(-23.2,-6.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#996666").ss(1,1,1).p("AjVgLICJimIBVAAIDNBRIgNDcIjWA2IhVAAIhzi0AhMixIDNBRIgODcIjVA2ABzB8IBWAAACBhgIBVAA");
	this.shape_10.setTransform(-14.8,-5.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#669999").s().p("AhiCyIDVg2IjVA2Ihzi0IAAgJICJimIBVAAIDNBRIhVAAIjNhRIDNBRIgODcIBWAAIjWA2gABzB8IAOjcIBVAAIgNDcgACBhgg");
	this.shape_11.setTransform(-14.8,-5.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#996666").ss(1,1,1,3,true).p("AhehDIAJgSIAKgSIA2A/IAKgSIAJgSIAJgSIA2A/IgKASIgJARIg1g+Ig2g/IAJgSIAKgSIAKgSIAJgSIAKgSIAKgSIA1A/IA2A/IA2A/IgKASIgKASIgJARIgKASIgKASIgJASIgKATIgKASIgJASIgKASIgKASIgJASIg1hAIgKATIgJASIg2g/Ig2g/IAJgSIAKgSIAJgSIAKgSIAKgSIA2A/IAJgSIAKgSIA1A+IgKASIgJASIgKASIgJATIg2hAIAKgSIAKgRIA1A+IA2BAAhiBoIg2g/IgBgBAhiBoIAKgSIAJgSIAKgTIg2g+AiYApIAKgSAhPBEIg2g/AAkiUIAKgSAgIjmIABABAARhwIAJgSIA2A/IA2A/AgkivIA1A/IA2A/IgKASIA2A+AgbjBIA1A/IAKgSIA2A/IgKASIgJASIA2A+ABkhnIgKASIA2A/AgChMIA1A/IA2A+AAHheIAKgSAgRjTIA1A/AguidIA1A/Ag4iLIA2A/AADBMIg1g/Ig2g+AgGBfIgJARIg2g/IAJgSIg2g+AATDVIgKARIg1g/Ig2g/AAcDCIgJATIg1hAIgKASAAcDCIg1g/Ig2g/AAvCeIg1g/AA5CMIg2hAAAgAWIA2BAABMBoIg2hAIg1g+Ig2g/AAmCwIgKASAAqAEIgKASABgBDIg2g/AhLhnIAKgS");
	this.shape_12.setTransform(-33.9,-26.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#669999").s().p("AgtCnIAKgSIA1A/IgKASgAgjCVIAKgSIg2g/IA2A/IgKASIg2g/IA2A/IgKASIg2g/IAKgSIAKgSIAKgTIg2g+IAJgSIAKgSIAKgSIA2A/IA1A+IgKASIg1g/IAKgRIgKARIg2g+IA2A+IgKASIA2A/IgJASIAJgSIAJgSIAKgSIA2BAIgKASIg2hAIA2BAIgKASIg1hAIA1BAIgJASIg1hAIA1BAIgKASIg1g/IAKgTIg2g/IAJgSIgJASIA2A/IgKATIA1A/IgKASgAg8AfIg2g+gAgjCVgAgjCVgAANA6IAJgSIAKgSIA2BAIgKASIg2hAIA2BAIgJASgAgPBwgAhjBoIg2g/IAKgSIAKgSIAKgSIA2A+IgKATIg2g/IA2A/IgKASIg2g/IA2A/IgKASgAg8AfIAKgSIA1A/IgJASgAAgAWIAJgSIgJASIg1g+IAJgSIA1A+IAKgRIAJgSIg2g/IAKgSIAKgSIg1g/IA1A/IgKASIg1g/IAKgSIAJgSIAKgSIA1A/IgKASIAKgSIA2A/IA2A/IgKASIg2g/IA2A/IgJASIg2g/IAJgSIg2g/IgJASIA2A/IgKASIg2g/IA2A/IgKASIAKgSIA2A+IgKASIg2g+IA2A+IgJASIg2g+IA2A+IgKASIg2g/IA2A/IgJATgABZhVIAKgSgAAjiUIg1g/gAhZBWgAhPBEgAANA6Ig1g+IAJgSIAKgSIA1A+IgKASIg1g+IA1A+IgJASgAhFAxgAAWAogAAgAWgABGgxIAKgSIA2A/IgKARgAgyANgAgyANgAgMg6IAKgSIA1A/IgKARgAgogEIg2g/IAJgSIAKgSIA2A/IgKASIg2g/IA2A/IgJASgAAzgNgAgChMIAIgSIA2A/IgJASgACPgWgAgfgWgAgVgogAhLhnIAJgSIAKgSIA2A/IgKASIg2g/IA2A/IgJASgABGgxgAgMg6gAgMg6gABQhDgAAaiCIAJgSIA2A/IgJASgAgChMgAgChMgAg4iLIAJgSIAKgSIA1A/IgKASIg1g/IA1A/IgIASgABZhVgAAGhegAAaiCg");
	this.shape_13.setTransform(-33.8,-26.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#666699").s().p("AhICHICQkOIABABIgKASIgKASIgJASIgKASIgKASIgJASIgKASIgJARIgJASIgKASIgKASIgJASIgKATIgJASIgKASg");
	this.shape_14.setTransform(-42,-35.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#996666").ss(1,1,1,3,true).p("AgSjTIAKgSIA1A/AgSjTIABAAIA0A/IA3A/IgKASIgKASIA3A+IgKASIgKASAgbjBIAJgSAgbjBIAAAAIA1A/IA2A/IA2A/IgJARAglivIAKgSAgvidIABAAIA0A/IAKgSIAKgSIAJgSIAKgSIA3A/IgKASIA2A/IgKASAhLhnIAAABIA1A+IAKgSIg1g/IAAAAIAJgSIABAAIA1A/IAIgSIA2A/IgJASIgKARIgKATIgJASIgJASIgKASIg1hAIAKgRIAJgSIg2g+IAAgBIAKgSIAKgSAhehDIAJgSAgMg6IAKgSIA1A/IA2A+IgKASIgKATIgJASIgKASIgJASIgKASIgJASIgKASIg1g/Ig2g/IAKgTIAJgSIAKgSIg2g+IAKgSIA2A/IA1A/IA1A/Ag4iLIAJgSIAKgSIA1A/IA2A/IgKASIA3A+AAfAXIA2A/ABfBDIg2g/Ig1g+AhZBWIAKgSIg2g/AgPBxIgKASIgJASIgKASIg3g/IAKgSIg1g/IACgFIAHgNIAJgSIAKgSIAKgSAgGBfIgJASIg2hAIg2g9IgBgBAAWApIg1g/IAJgSIA1A/AAvCeIg1g/Ig2hAIg2g9IAAgBAAmCwIg1g/AgiCVIg3g/ABMBoIg2g/AADBNIgJASAA5CMIg2g/AhjBoIg1g/IAHgOIADgEAATDUIgKASIg1g/AATDUIg1g/AAcDCIgJASABkhnIA2A/IgKAS");
	this.shape_15.setTransform(-50.7,-45.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#666699").s().p("AACgEIgCAEIgBAFg");
	this.shape_16.setTransform(-65.1,-43.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#669999").s().p("AgsCnIg2g/IAKgSIAJgSIAKgTIAJgSIA2BAIgJASIAJgSIg2hAIAKgSIg2g+IAJgSIAKgSIAAABIA2A+Ig2g+IAAgBIAJgSIABABIA1A+Ig1g+IgBgBIAKgSIAKgSIAJgSIABAAIA0A/IgIASIAIgSIAKgSIA2A/IAKgSIA2A/IgKARIg2g+IA2A+IgKASIg2g+IAKgSIgKASIg2g/IA2A/IgJASIg1g/IA1A/IgKARIg1g+IAKgSIgKASIg1g/IgBAAIABAAIA1A/IA1A+IgKATIAKgTIA2A/IgKATIg2g/IA2A/IgJASIg2g/IAJgSIg1g/IAKgSIgKASIgJASIAJgSIA1A/IgJASIg1g/IA1A/IgKASIg1g/IAKgSIgKASIg2g/IA2A/IgJARIAJgRIA1A/IgJASIAJgSIA2A/IgJASIg2g/Ig1hAIA1BAIgJASIA1A/IgJASIg1g/Ig2hAIA2BAIgKASIg2g/IA2A/IgJASIg2g/IA2A/IgKASIAKgSIA1A/IgKASgAg4iLIA2A/Ig2g/IAAAAgAgiCVIAJgSIA1A/IgJASgAgZCDIAKgSIA1A/IgKASgAgGBfIAJgSIA2A/IgKASgAgiCVgAgZCDgAAMA7IAKgSIA2A/IgKASgAgPBxgAiYApIAHgOIADgEIACgFIAHgNIAKgSIAJgSIABABIA1A9IgJASIg2g9IAAgBIAAABIA2A9IgKATIg2g/IA2A/IgJASIg2g/IA2A/IgKASgAhYBWgAADBNgAhPBEgAApAEIAKgRIA2A+IgKASgAAMA7gAAzgNIAJgSIA2A+IgJASgAhFAxgAAWApgAg8AfgAhxgeIgBgBIAKgSIA2A+IgKASgAApAEgABQhDIAKgSIA2A/IgKASgAAzgNgAAzgNgABahVIgKASIg2g/IA2A/IgKASIg2g/Ig1g/IA1A/IgKASIg0g/IgBAAIAKgSIAKgSIAAAAIA1A/Ig1g/IAAAAIAKgSIAAAAIA1A/Ig1g/IAAAAIAKgSIA1A/IgKASIgKASIgKASIAKgSIAKgSIA2A/Ig2g/IAKgSIA2A/IgKASIAKgSIA2A/IgKASgAA8gfgABQhDgAAGheg");
	this.shape_17.setTransform(-50.7,-45.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#996666").ss(1,1,1,3,true).p("AhjBoIg2g/IAFgJQABgDACgCIACgEIADgFQAAgBABgBQADgGADgFIAJgSIAKgSIAKgSIAJgSIAKgSIAJgSIABABIA1A+IAKgSIAKgSIA1A/IgJARIgKATIgKASIgJASIA2A/IgKASIgKASIg1g/IgJASIgKASIg2g/IAJgTIg1g9IgBgBAgvidIAKgSIA1A/IAKgSIAJgSIAKgSIA3A/IA2A/IgKASIgKASIgJARAg4iLIAAAAIA2A/IAIgSIAKgSIA3A/IA2A+IgKASIgKASIgJASIgKATIgKASIg2g/Ig1g/IAJgSIA2A/IA2A/AgMg6Ig1g/IgBAAAhMhnIAKgSIAKgSIAJgSIABAAIA0A/IA3A/IgKASIA2A+AgbjBIAAAAIA1A/IA2A/IgJASIgKASIA2A+AgSjTIABAAIA0A/IA3A/IgKASIA2A/AgbjBIAJgSIAKgSIA1A/AglivIAKgSAAqAEIg2g+Ag8AfIg2g9IAAgBAgfgWIg2g+IAAgBAgyANIAJgRIA2A/IgKASIgJASIg2hAIAKgSIg2g+AhfhDIA2A/IAKgSAgiCVIg3g/IAKgSIg2g/AhjBoIAKgSIg2g/AA5CMIg2g/Ig1hAAgPBxIg3hAIAKgSAgZCDIgJASIgKASIg3g/ABahVIA2A/ABMBoIgJASABgBDIg2g/ABkhnIgKASAATDUIgKASIg1g/AAmCwIgKASIgJASIg1g/AAvCeIgJASIg1g/AAcDCIg1g/");
	this.shape_18.setTransform(-67.5,-65.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#669999").s().p("AgsCnIAKgSIA1A/IgKASgAgiCVIAJgSIg2g/IAJgTIg1g9IgBgBIABABIA1A9IgJATIg2g/IA2A/IgKASIg2g/IA2A/IgKASIg2g/IAFgJIADgFIACgEIADgFIABgCIAGgLIAJgSIAKgSIAAABIA2A9Ig2g9IAAgBIAKgSIAJgSIAKgSIAAABIA2A+Ig2g+IAAgBIAJgSIABABIA1A+Ig1g+IgBgBIAKgSIAKgSIAJgSIAKgSIAKgSIAJgSIABAAIA0A/Ig0g/IgBAAIAKgSIA1A/IgKASIAKgSIA3A/IA2A/IgKASIg2g/IAKgSIgKASIA2A/IgKASIg2g/Ig2g/IA2A/IgJASIg3g/IA3A/IgKASIg3g/IAKgSIAKgSIAJgSIgJASIgKASIg1g/IA1A/IgKASIgIASIg2g/IAAAAIAAAAIA2A/IgKASIg1g/IgBAAIABAAIA1A/IgKASIA2A/IAKgTIAJgRIA2A+IgJASIg2g/IA2A/IgKATIg2g/IgKASIA2A/IgJASIg2g/IAJgSIg1g/IAJgSIgJASIgKASIg2g/IA2A/IgJARIAJgRIA2A/IgKASIg1hAIg2g+IA2A+IgKASIgKASIAKgSIA2BAIgJASIg3hAIA3BAIgKASIAKgSIAJgSIg2hAIAKgSIA1BAIgJASIAJgSIAKgSIg2g/IAKgSIA1A/IgJASIA2A/IgKASIg2g/IA2A/IgKASIg1g/IA1A/IgJASIg1g/IA1A/IgKASIg1g/IA1A/IgJASgABQhDIAKgSIg3g/IA3A/gAguidIA0A/Ig0g/IgBAAgAgbjBIA1A/Ig1g/IAAAAIAAAAgAgsCnIg3g/IAKgSIAKgSIA2A/IgJASIg3g/IA3A/IgKASgAgPBxgAAWApIAKgSIA2A/IgKASgAhZBWgAADBNgAhPBEgAAzgNIg1g/IAIgSIA3A/IgKASIAKgSIA2A+IgKASgAAWApgAA9gfIAKgSIA2A+IgKASgAgWgoIAKgSIA2A+IgKATgABHgxIAJgSIA2A/IgJARgAgyANgAAqAEgAgMg6IAKgSIA1A/IgJARgAgpgEgAAzgNgACQgWgAA9gfgAA9gfgAgMg6gABQhDgAgChMgAAQhwg");
	this.shape_19.setTransform(-67.5,-65.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#666699").s().p("AACgEIgCAEIgBAFg");
	this.shape_20.setTransform(-81.8,-63.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#996666").ss(1,1,1,3,true).p("AAFh6IASAIIgJBPIATAJIATAIIATAIIATAIIATAHIATAIIgJBQIgTgIIgTgIIgJBPIgTgIIgTgIIgTgIIAJhQIgTgIIgIBPIgTgIIgTgIIgTgIIgTgIIgTgIIgTgIIgTgJIgSgIIgBAAIAJhOIAJhQIABAAIATAIIAJhPIATAIIATAIIASAIIAUAJIATAIgAiAizIABAAIATAIAiAizIAAgBAh1hcIATAJIAJhQAiJhkIAJhPAiIhkIAJhPAhZADIAKhOIAJhQAhZADIgTgHIgSgIIgTgIIgBAAAgWgzIATAIIARAIIgJBPIgRgIIgUgIIgSgIIgTgJIAJhOIASAIIAUAIIgKBPIgJBPAgMAkIAJhPIAIhPAgyAUIAIhPIAKhPAh+gMIAJhQAhsgEIAKhPIATAIIATAIIAIhQAiRgUIAJhQAhFALIgUgIAgNiCIgJBPAAqhqIATAIIATAIIgJBQIgJBOIgTgIIgJBQABjhRIATAIIgJBOIgJBQIgJBPABjhRIgJBPIgJBPIgTgJIgJBQACcg5IgJBPIgJBPIgJBQIgTgJIgTgIIgTgIACJhBIgJBOIATAJACcg5IAAAAACJhBIATAIAA9hiIgJBQIgJBOIgTgIIAJhOIAJhQAB2hJIATAIABQhaIATAJAAXhyIATAIAB3BdIgJBPACKBlIgTgIAAPCEIgSgJAhiBTIAJhQAgWBzIAKhPAg8BjIAKhPAhPBbIAKhQAiaA6IAJhOAiIBCIAKhOAh1BLIAJhP");
	this.shape_21.setTransform(-22.8,45.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#669999").s().p("ABuCsIAJhQIATAJIgJBPgABuCsIgTgIIAJhQIATAIIgJBQgABbCkIgTgIIAJhPIATAHIgJBQgABICcIgUgJIAKhPIAJhOIgJBOIgTgIIAJhOIgJBOIATAIIgKBPIgTgHIAKhQIgTgIIATAIIgKBQIgTgIIAKhQIAJhPIATAJIATAIIgTgIIAJhQIgJBQIgTgJIAJhPIgJBPIgTgIIgJBPIATAIIgKBQIgSgJIAJhPIgSgJIAJhOIgJBOIgTgIIATAIIgJBQIgTgIIAJhQIgJBQIgTgIIAKhQIgKBQIgTgJIAKhPIATAIIASAIIAJhOIATAIIASAIIgSgIIgTgIIAJhQIgJBQIgSgIIAJhPIgJBPIgTgJIAJhPIgJBPIgJBPIgTgIIAJhOIgJBOIgTgHIATAHIgKBPIgTgIIAKhOIgKBOIgTgIIAKhOIgKBOIgTgIIAKhOIATAIIATAIIAJhPIATAIIATAHIgTgHIAJhQIgJBQIgTgIIAJhQIgJBQIgTgJIATAJIgJBPIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgBAAIABAAIgKBOIAAAAIAJhOIAJhQIAJhQIABAAIATAJIgJBPIgTgIIAJhQIgJBQIgBAAIABAAIATAIIAJhPIATAIIATAIIATAIIATAJIASAHIASAIIgIBQIAIhQIATAIIgJBQIAJhQIATAJIATAIIATAIIgJBQIATAIIATAHIgTgHIAJhPIATAIIATAIIgJBOIATAIIgTgIIAJhOIATAIIgJBOIgJBQIgTgJIAJhPIgJBPIgTgIIAJhPIATAIIgTgIIgJBPIgTgHIAJhPIgJBPIgTgJIATAJIgJBPgABtAFIAJhOgAgEB7IgSgIIAJhQIASAJIgJBPgAhPBaIgTgIIAKhPIATAIIgKBPgABRBNgAAYA0gAAYA0IgTgIIAJhPIATAIIgJBPgAAFAsgAgyATIAJhOIASAIIgJBOgAgyATIgTgIIAJhPIATAJIgJBOgAhFALgAhYADgABagCIgTgIIAJhQIATAJIgJBPgAiRgUgAAhgbgAAhgbgAAhgbgAiIhkg");
	this.shape_22.setTransform(-22.8,45.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#666699").s().p("AB7A1IgTgIIgTgIIgTgJIgTgHIgTgIIgTgJIgRgHIgTgIIgTgIIgTgJIgTgIIgTgIIgTgIIgTgIIAAAAIAAgBIEbB6IAAAAg");
	this.shape_23.setTransform(-21.5,33.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#996666").ss(1,1,1,3,true).p("AA9hiIATAIIAAAAIgJBPIATAJIATAHIATAIIATAIIgJBQIgTgJIgTgIIgJBQIgTgIIgTgIIgTgIIgTgIIAJhQIgTgJIgIBQIgTgIIgTgIIgTgIIgTgIIgTgIIgTgIIgSgJIgTgIIgBAAIAJhPIAJhPIAJhQIABAAIATAIIASAJIATAIIATAIIATAIIATAIIgJBQIgJBOIgJBQAAXhzIATAJIATAIIgJBPIATAIIgJBPIgJBQAAXhzIAAABIgJBPIATAIIATAIIgJBPIgTgIIAJhPIAJhPAgEgrIAIhPIAAgBIATAIABjhSIgJBQIgJBOIgTgIIgTgIIgJBQAB2hKIAAABIgJBOIgJBPIgTgIIgJBQAB2hKIATAIIAAABIgJBOIgJBPIgJBQACJhCIATAJIgJBOABjhSIATAIABQhaIATAIAg9hEIAJhPIAAAAAiIhkIAJhPIAAgBAh1hcIAJhPIAAgBAiIhkIATAIIASAIIATAIIATAIIATAJIATAIIATAIIASAIIgJBOIgSgIIgTgIIgTgIIgTgIIgTgIIAJhPIAJhPAiJhkIABAAAh+gNIgTgIIgBAAAhsgEIgSgJIAJhPAgNAjIAJhOAgzATIAJhOIAJhQAhGALIAJhPAiRgVIAJhPAhsgEIAJhQIAJhPAhZADIgTgHACKBlIgJBQIgTgJIgTgIAiHBCIAJhPAiaA6IAJhPAgWBzIAJhQAAPCEIgSgJAhiBTIAJhQAhPBbIAJhQAg8BjIAJhQAh1BLIAJhPAgOiDIASAI");
	this.shape_24.setTransform(-20,20.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#669999").s().p("ABuCsIAJhQIgTgIIAJhPIATAIIATAIIgJBQIgTgJIAJhPIgJBPIATAJIgJBQgABuCsIgTgIIAJhQIATAIIgJBQgABICcIAJhQIATAIIgJBQgABICcIgTgIIAJhQIATAIIgJBQgAA1CUIgTgIIAJhQIgTgIIAJhPIgJBPIATAIIgJBQIgTgIIAJhQIgTgJIAJhOIATAIIATAIIATAIIgTgIIAJhPIgJBPIgTgIIgTgIIAJhPIAAgBIAAABIgJBPIgSgIIASAIIgJBOIATAJIgJBQIgSgJIAIhQIgSgIIAJhOIgTgIIAJhQIASAIIAAABIgIBPIAIhPIAAgBIATAIIATAJIgJBPIAJhPIATAIIATAIIAAAAIgJBPIATAJIATAHIgTgHIAJhQIATAIIAAABIgJBOIAJhOIAAgBIATAIIAAABIgJBOIAJhOIAAgBIATAJIgJBOIgTgIIgTgIIgJBPIgTgIIAJhOIgJBOIgTgIIAJhPIgJBPIgTgIIAJhPIgJBPIATAIIgJBQgAgDB7IgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhPIATAHIgTgHIAJhQIgJBQIgSgJIASAJIgJBPIgSgJIAJhPIgJBPIgTgIIAJhPIgJBPIgBAAIAJhPIABAAIgBAAIAJhPIAJhQIABAAIATAIIASAJIATAIIATAIIAAAAIgJBPIAJhPIAAAAIATAIIATAIIgJBQIgTgIIAJhQIgJBQIgTgJIgTgIIAJhPIgJBPIgTgIIAJhPIgJBPIgSgIIAJhPIAAgBIAAABIgJBPIgTgIIATAIIgJBPIgTgIIAJhPIAJhPIAAgBIAAABIgJBPIgBAAIABAAIgJBPIATAIIAJhPIASAIIATAIIgJBPIATAIIATAIIATAIIATAIIASAIIgIBQgAB3BcgABkBUgABkBUgABRBMgAA+BEgAArA8gAAYA0gAggAbIgTgIIAJhOIATAIIgJBOIAJhOIATAIIgJBOgACTAVgAgzATIgTgIIAJhPIATAJIgJBOgAhGALIgTgIIAJhPIATAIIgJBPgABagCIgTgJIAJhPIAAAAIATAIIgJBQgAAOgjgAgXgzgAgqg7gAhQhMgABjhSgAiIhkg");
	this.shape_25.setTransform(-20,20.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#996666").ss(1,1,1,3,true).p("AibA6IAAAAIAJhOIAJhQIABAAIATAIIAJhPIASAIIATAIIATAIIATAJIAUAIIARAIIATAIIATAIIATAIIATAIIgJBQIATAIIATAHIATAIIATAJIgJBPIgTgIIgTgIIgTgIIgTgJIgJBQIgUgIIgTgIIgRgJIgTgIIgTgIIgTgIIgTgIIgTgIIgTgIIgTgJIAKhOIgTgIIgBAAAB2hJIATAIIgJBOIgJBQIgJBPIgTgIIgUgIIgSgIABjhRIgJBPIgJBPIgKBPAB2hJIgJBOIgJBQIgJBPABjhRIATAIACcg5IAAAAIgJBPABQhaIATAJACJhBIATAIAh/izIAAgBAh/izIAAAAIATAIAiJhkIAKhPAiIhkIAJhPAhQhLIATAIIAJhQAhrgEIgTgIIAJhQIASAJIAJhQAhGALIgTgIIgSgHIAIhPIATAIIAJhQAgzAUIgTgJIAJhOIATAIIATAIIgJBPIgTgIIAJhPIAJhPAhZADIAJhOAgNAkIgTgIIgJBPAgNAkIAKhPIARAIIATAJIATAIIgJBOIgTgIIgTgIIgIBPAgXgzIAUAIIAHhPAAhgaIAJhQAAXhyIgJBPIgJBPIgSgIAgNiCIgKBPAiRgUIAJhQAAOCEIAKhQIAJhOAArA8IgKBQACKBlIgJBQIgTgJAA9hiIgJBQIATAIIgJBOIgTgIAgWBzIAJhPAg8BjIAJhPAhPBbIAJhQAhiBTIAJhQAh1BLIAKhPAibA6IAKhOAiIBCIgTgI");
	this.shape_26.setTransform(-25.7,70.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#666699").s().p("AB7A1IgTgIIgTgIIgTgIIgTgIIgTgIIgTgJIgRgHIgTgIIgTgIIgTgJIgTgIIgTgIIgTgIIgTgIIAAAAIAAAAIEbB5IAAAAg");
	this.shape_27.setTransform(-24.3,58.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#669999").s().p("ABtCsIAKhQIgKBQIgTgIIAKhPIgKBPIgSgIIAJhPIgJBPIgTgIIAJhQIATAJIATAIIATAHIATAJIgKBPgAAiCMIAJhQIgJBQIgTgIIAJhQIATAIIATAIIgJBQgAAPCEIgTgJIAJhQIgSgIIAJhOIgJBOIgTgIIATAIIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgTgIIAJhOIATAIIgJBOIATAIIAJhOIATAIIASAIIgJBOIAJhOIATAIIgJBPIgTgJIATAJIgJBQgAgEB7IgSgIIAJhQIASAIIgJBQgAB3BcIAJhPIATAJIgJBPgAhPBaIAJhPIgJBPIgTgIIAJhPIgJBPIgTgIIAKhOIgKBOIgSgIIAJhOIATAIIgTgIIAJhQIAJhQIgJBQIgTgIIAJhQIgJBQIAAAAIAAAAIgJBQIAJhQIATAIIgJBQIgTgIIAAAAIAAAAIATAIIgJBOIgTgIIAJhOIgJBOIgBAAIAKhOIAJhQIAJhQIAAAAIATAIIATAJIASAIIATAIIATAJIgJBPIAJhPIATAIIgJBPIgTgIIATAIIgJBOIgTgIIAJhOIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgSgIIAJhQIgJBQIgTgJIATAJIgJBPIASAHIATAIIATAIIgJBQgABkBVIAJhQIATAIIgJBPgABRBNIAJhPIgJBPIgTgJIAJhOIgTgIIgJBOIgTgIIAJhPIATAJIgTgJIAJhPIgJBPIgTgIIAJhQIATAJIATAIIgJBQIAJhQIATAIIgJBQIATAIIATAHIgTgHIAJhQIATAJIATAIIgJBOIAJhOIATAIIgJBPIgTgJIgTgIIAJhOIgJBOIgJBQgAA+BEIgTgIIAJhOIATAIIgJBOgAgzATgAhGALIgTgIIAJhOIATAIIgJBOgAhZADIgSgHIAJhPIASAIIgJBOgABagCIgTgIIAJhQIATAIIgJBQgABHgKgAAOgjIgSgIIAIhQIATAIIgJBQgAgXgzIAJhPIASAHIgIBQgAgXgzgAgXgzgAhQhLgABjhSgAhihTgAhihTgAiIhkgAAEh7g");
	this.shape_28.setTransform(-25.7,70.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.8,-89.4,167.7,178.8);


(lib.juno = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.juno_animated("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:76.9},71,cjs.Ease.linear).to({startPosition:0},25,cjs.Ease.linear).to({rotation:0},71,cjs.Ease.linear).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.8,-89.4,167.7,178.8);


(lib.earth = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.16,0.16);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(100,178,57,0.957)").s().p("AAAABIAAgBIABABIgBAAg");
	this.shape.setTransform(-2.6,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(117,207,53,0.996)").s().p("AAAAAIAAAAIAAABg");
	this.shape_1.setTransform(-2.8,7.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7BDA37").s().p("AAAABIAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAgBABg");
	this.shape_2.setTransform(-0.5,8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(105,188,54,0.953)").s().p("AABAAIgCAAIADAAg");
	this.shape_3.setTransform(-2.1,7.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6DC137").s().p("AAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(-0.5,4.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#71C936").s().p("AgBAAIABAAIACABIgDgBg");
	this.shape_5.setTransform(-2.3,4.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#74CE35").s().p("AAAAAIABAAIgBABIAAgBg");
	this.shape_6.setTransform(-2.5,3.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#73CB36").s().p("AAAABIAAgBIAAABg");
	this.shape_7.setTransform(-2.9,3.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#72CA36").s().p("AAAAAIABAAIAAABIgBgBg");
	this.shape_8.setTransform(-2.7,4.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#75CF35").s().p("AAAAAIABAAIAAAAIgBABg");
	this.shape_9.setTransform(-4.3,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#78D434").s().p("AAAABIAAgBIABABg");
	this.shape_10.setTransform(-2.7,1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#75D035").s().p("AANARIACAAIAAABgAgNgPIABgCIAAACg");
	this.shape_11.setTransform(-2,3.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6FC537").s().p("AgLAUIAAgDIACADgAAHgCQgCgFgFgDQAFACAAACIADACQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAIgDgBgAAJgSIABgBIABAAIgCADg");
	this.shape_12.setTransform(-2,3.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6ABD38").s().p("AAAAAIABAAIgBABg");
	this.shape_13.setTransform(-0.2,1.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#74CE36").s().p("AAAAAIABAAIgBABg");
	this.shape_14.setTransform(0.4,1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#75CF36").s().p("AAAAAIABAAIgBABg");
	this.shape_15.setTransform(0.8,0.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#78D534").s().p("AACABIgDAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABg");
	this.shape_16.setTransform(1.6,0.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(22,45,79,0.992)").s().p("AgFALIAAgDIAAgBIAAgCIACgFQAAABABAAQAAAAAAAAQABAAAAAAQABAAAAgBIgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAgBAAAAIAEACIABAAIgBgEIABgEIABAAIAAgEIACAJIgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAIgBAAIgBAAIABAFIgBAAIAAADIgCgBQAAAAgBAAQAAAAAAABQAAAAgBABQAAAAAAAAIgCAEQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBg");
	this.shape_17.setTransform(7.4,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#77D235").s().p("AgLAcIACAAIAAAAIAAABIgCgBgAALgcIABAAIAAABg");
	this.shape_18.setTransform(1,2.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#76D035").s().p("AAAAAIABAAIgBAAIAAAAg");
	this.shape_19.setTransform(0.8,-1.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6EC337").s().p("AAAAAIABAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAg");
	this.shape_20.setTransform(0.2,-2.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#77D334").s().p("AAAAAIABAAIAAAAIgBAAg");
	this.shape_21.setTransform(1.3,-2.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#73CC36").s().p("AgaASIAAgBIABAAIgBACIAAgBgAAbgSIABABIgBAAg");
	this.shape_22.setTransform(-1.6,-1.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#70C737").s().p("AgCAQIgCgFIgBgDIABgFIABAAIgEgIQgBgCABgDIgBAAQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIgCgCIAAgCQAAgBABAAQAAAAABgBQAAAAAAgBQABAAAAgBIADAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQABABAAAAIACAAIAAgCIAFADIAAABIAEAHIABADIACACIgCADQgDAAgBADIgCADQAAAEACABIgFAAgAAJAHQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAABAAQABgBAAAAQABAAAAABQABAAAAAAIABAAIAAACQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgEABQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBg");
	this.shape_23.setTransform(3.3,-2.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#70C637").s().p("AgUAYQABAAAAAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIABABIAAABQgEAAgCgEgAAvgVQgBABAAAAQAAABAAAAQAAAAAAAAQAAAAABAAIAAADQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIABgEIAAgCIAAgCIABABQAAABAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAFAHIgCAAIgBADIgDgFgAg0gYIAAgCIACAAIgBACIgBAAg");
	this.shape_24.setTransform(1,1.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#71C836").s().p("AAeAUIAAgGQAAAAAAgBQAAAAABAAQAAAAAAAAQAAABAAAAIACAHIgDgBgAAVgHIACAAIABAAIABgFIgDgFQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQACAAADACIABAEIABABIAAACIAAABIABAEIAAACQgBAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgCABIgGgFgAAIgEIABAAQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAAABIgDgCgAgggDIADgEIgCAEIgBABg");
	this.shape_25.setTransform(-0.8,-1.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6ABC38").s().p("AAAAAIABAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAABAAAAg");
	this.shape_26.setTransform(-2.6,-3.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6BBE38").s().p("AgCACIAFgEIgFAFg");
	this.shape_27.setTransform(-2,-4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#75CE35").s().p("AAMADIAAABIgBABIABgCgAgLgEIABAAIgBABg");
	this.shape_28.setTransform(-0.4,-4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("rgba(112,199,55,0.996)").s().p("AAOBGIgFAAIgEAAQAAAAABgBQAAAAgBAAQAAAAAAAAQAAAAgBAAIAAABIgCAAIAAgBIgDAAIgCAAIgCgCIgDAAIgEgBIgBAAIgBgBIgDgBIgBAAIABgCIAAAAIABAAIACgDIgCgBQgCgHgDgFIABAAIgBgDIABgBIAAgCIADAAIADgBIABgBIACgEIgFgCIAAgBIgBgBIAAAAIgBAAIAAgBIgBgCIAAgCIAAgDIgCgEIgEgEIgCgDQAAAAAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgBgBIAAgBIgBgCIAAgBIgDgFIAAAAIABgBIAAgBQACgDAAgDIAAgFIABgDQAAgBgBAAQAAAAAAABQgBAAAAAAQAAABgBAAIAAADQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAgBAAIABABIgBAAIAAABIgBgFIABgDIAAgBIABgGQABAAAAABQAAAAAAgBQABAAAAAAQAAgBAAAAIgCAAIACgBIABgBIACgEIAAgBIAAgBQAFgGAGgCQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIgCAAIAAgBIACAAIABgDIABgCIAGgGIABgBIABgBIAAgFIgCgEQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAABABAAQAAAAAAAAQABABAAAAQAAAAABAAIACgCIABgBIABAAIADABIACgBIADABIABAAIADADIAAABIgBACIAAAEIAAACIAAABIABABQABAFACADIABAAIAAgCQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBAAIAAgCIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIABAEQAAAAAAAAQAAAAAAAAQAAABAAAAQAAABAAAAIgBACIAAABQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIABgCIABAAIAAACIgBABIAAABIABABIACAAIAAABIgBAAIABABIAAABIgGACQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABIgCABIgBABIAAABIgBAAIAAABIABABIgBAAIACADIABABQABAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAABQAAABABAAQAAABAAAAQAAAAAAABIAAABIADgFIAAAAIACgBIgBAAIABgBIAAgBIABgBIAAgDIABgBQAEABABADIAAACQADACABADIAAABIABABIgBAAIABABQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABIgBABIAAABIgCAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIgBAAIgGABIACAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIABABIABABQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAIAEAAIgGABIgBAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAAAABIgBAAIAAABIgDABIgCAAIAAAAIgCABIgBABIAAABIgCAAIAAACIgEABQgBAAAAgBQgBAAAAAAQAAAAAAAAQAAABAAAAIgBAAIgBABIAAABIgBABIAAACQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIAAgDIAAgCIAAgBIgGgEIgBAAIgDgDIgCAAIgBAAIAAAAIgCAAIgCACIgBAAIAAABIgCACIAAABQAAAEAEADIABAAIAAgCIACAAIADAAIAAADIgEADIABACIABAAIACACIAAABQABAAAAAAQABABAAAAQAAABAAAAQgBABAAAAIgBAAIgCACIAAAAIAAACQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAIABABIgBAAIADACIAAAAIAAABIAFgBIACAAIACABIABABQAAABAAAAQABAAAAAAQAAABAAAAQAAAAABAAIABAAIABABIABABIABAAIAEABIgCAAIADABQACAEAFACIAAABIACAAQACABAAAEIAAABIABABQABAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIACAAIACABIACAAIAAABIACAAIACABIAAACQgFACgDADIgCADIgKABg");
	this.shape_29.setTransform(-1,1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#74CD36").s().p("AgVArIAAgBIADAEIgDgDgAAVgRIABgBIgBACgAADgtIACAAIACABIgEgBg");
	this.shape_30.setTransform(-1,-1.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(112,199,54,0.996)").s().p("AATA+IAAgFQACgNAFgHIABgGIADgDIABgCIgDACQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgBAAIgBgDIAAgCIABAAIgBgBIAAgCIABgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIgCgDQAAgBAAgBQAAgBAAAAQABgBAAAAQAAgBAAAAIAAgDIAAgCIgBgCQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAgBQAAAAgBgBIABgHIgCgCQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIAEAJIgBAAQgBAAAAAAQAAgBgBAAQAAAAAAABQgBAAAAAAQgCgBgCgEIAAgCIgEgJQAAAAgBgBQAAAAAAgBQAAAAAAAAQABAAAAAAIAEAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIgDgBQAAgBAAAAQgBAAAAgBQAAAAABAAQAAgBAAAAIgBgCQgBgFgEgEIgDAAQgDgDgDAAIgBAAIgFgDQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIgBAAIgDgBIgGgDIgBABIAAACQgEgBgCgBQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABQgDgBgDgBIgBADIgEAAQgEADgEgDQABAAABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIAAgDQAAAAABgBQAAAAAAAAQABAAAAAAQAAgBABAAIACAAIABgBIACAAIAAgCIAFAAIABAAIAAgCQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAIAAgBIAVAGIAIAFQANAGAJALQAJAKAFAPIADAKIAAAEIgBAAIgBADIABAEIgBAAIgEgCQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIABACQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAIgCAEIAAACIAAACIAAADQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIADgDQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADABIAAgDIABAAIgBgEIABAAIABgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIABAAIAAABIAAAEIAAADIAAADIAAADIgDAOQgDAQgKALQgDAAgDACIgDgCg");
	this.shape_31.setTransform(3.7,-1.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("rgba(21,45,79,0.996)").s().p("AAXBNQAEgDAEgCIAAgCIgCgBIgBAAIAAgBIgCAAIgDgBIgCAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgBgBIAAgBQAAgDgDgBIgCAAIAAgCQgEgCgDgDIAAgBIgBAAIgDgCIgBgBIgBAAIgBgBIgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIgBgBIgDgBIgCAAIgEABIAAgBIgBAAIgCgCIgBgCQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgBIAAAAIACgCQABgBAAAAQAAgBAAAAQAAgBAAAAQgBAAgBAAIAAgCIgBgBIgBAAIgBgCIADgDIAAgDIgCAAIgCAAIAAACIgCAAQgDgDAAgEIAAgBIABAAIAAgCIAAgBIABAAIADgCIACAAIABAAIABAAIAEADIABAAIAFAEIAAABIAAACIAAADQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBIAAgCIABgBIACgCQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAABIAEgBIABgCIAAgBIABgBIADgBIACgCIACAAIABgBQABgBAAAAQABAAAAAAQABAAAAABQABAAAAABIABAAIAFgBIABAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAIgBgBIgBgBQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIgCAAIAFgBIABAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIACAAIAAgBIABAAQAAAAAAgBQABAAAAgBQAAAAgBgBQAAAAAAgBIAAgCIgBgBIAAgBQgBgCgEgCIAAgDQgBgCgDgBIgBABIAAACIgCABIAAACIgBABIAAABIgBAAIgCAEIAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAgBIgBgBIAAgBQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIgBgBIAAgBIABAAQABAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAgBIACgBQAAAAAAAAQAAAAAAAAQABAAAAAAQABgBAAAAIAHgBIAAgBIAAgBIAAgBIgCAAIgBgBIABgDIAAgBIgBgBIAAABIgCABQAAABgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgBIABgBIAAgBQABgBAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIgBgEQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgCAAIAAACIABAAQAAABgBAAQAAABAAAAQAAABAAAAQABAAAAABIAAACIgBAAQgDgEgBgEIgBgBIAAgBIAAgCIAAgEIABgCIAAgBIgCgDIgBAAIgCgBIgBAAIgCABIgDgBIgBAAIgCABIgCACQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAABAAAAQAAABAAAAQABABAAAAQABAAAAABIACAEIAAAFIgBAAIAAABIgBABIgGAFIAAABIgBACIgBACIgBAAIAAABIAAACQgHACgEAFIAAACIAAAAIgEAEIAAABIgBABIAAACIgBAFIAAABIgBAEIABADQAAABAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIgBAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAIAAgDQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIgBAEIAAADQAAAEgBADIgBABIAAAAIAAACIACAFIAAABIABACIAAABIABABQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIACADIADAEIAAABIADADIAAADIAAACIAAABIABAAIAAABIABAAIAAABIABACIAFACIgDADIgBABIgCACIgEAAIAAACIgBABIAAACQAEAGACAHIABABIgBACIgBAAIAAABIgBAAIAAACIgDgCQgNgFgLgJQgKgLgHgNQgHgNgBgSIAAgGIAAgCIAAgDQADgQAGgOQAIgNALgJQAJgIAMgGIADgBQALgDAMgCIAIAAIADAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAAAgBIAAABQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABIgBACIgBAAIgEAAIAAACIgCAAIgBABIgCAAQgBAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAIAAADQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAQADADAEgDIAEAAIABgDQACABAEABQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAQACABAEABIAAgCIABgBIAFADIAEABIABAAQAAAAgBABQAAABABAAQAAABAAAAQABABAAAAIAFADIACAAQADAAADADIADAAQAEAEABAFIABACQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAABABIADABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEAAQgBAAAAAAQAAAAAAAAQAAABAAAAQAAABABAAIAEAJIAAACQABAEADABQAAAAAAAAQABgBAAAAQAAAAABABQAAAAABAAIABAAIgEgJQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIABAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIACACIgBAHQAAABABAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABIABACIAAACIgEgHQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIgBgBIAAACIAAACIgBAEQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAAgDQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIAEAFIABgDIABAAIAAADQAAAAAAABQgBAAAAABQAAAAAAABQAAABAAAAIACADQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgBABIAAACIABABIgBAAIAAACIABADIABAAQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIADgCIgBACIgDADIgBAGQgGAHgBANIAAAFIADACQADgCADAAIgBACQgIALgMAIQgIAFgLAEIgKADIACgDgAgDAkQABAEAEAAIAAgBIgBgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAAAAAAAIgCgBIgBABgAgGAiIADABQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBIgDgCQgBgCgEgBQAEADADAFgAAcABIAAAHIADABIgCgIIAAgBIgBABgAAqgJQgDgBAAgEIADgDQABgDADAAIABgDIgBgDIgBgDIgEgHIAAgBIgGgDIAAACIgCAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQAAABgBAAQAAABgBAAQAAABgBAAQAAAAgBABIAAACIADACQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIABAAQgBADABACIAFAJIgBAAIgBAFIABADIACAFIAGAAIAAAAgAAxgTQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAABABAAQAAABAAAAQAAAAABAAIAEgBQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAAgCIgBAAIgCgBIgCABgAAZgPIACgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAAgCIgBgEIAAgBIAAgCIgBgBIgBgEQgDgCgCAAQAAABgBAAQAAABAAAAQAAABAAAAQABAAAAABIADAEIgBAFIgBAAIgCAAIAGAFgAgOAtIAAAAg");
	this.shape_32.setTransform(-0.6,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.earth, new cjs.Rectangle(-8,-8,16,16), null);


// stage content:
(lib._06End2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// earth
	this.instance = new lib.earth();
	this.instance.parent = this;
	this.instance.setTransform(403.3,108);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[403.3,108,403.1,107.8,402.9,107.6,402.3,106.9,401.4,106.2,395.4,100.8,386.2,96.1,360.1,82.9,323.3,82.9,286.4,82.9,260.4,96.1,234.3,109.3,234.3,128.1,234.3,146.8,260.4,160.1,286.4,173.3,323.3,173.3,360.1,173.3,386.2,160.1,412.3,146.8,412.3,128.1,412.3,119.6,406.9,112.2,406.6,111.7,406.2,111.2,406,111,405.8,110.7]}},47,cjs.Ease.linear).wait(1).to({x:403.3,y:108},0).to({guide:{path:[403.3,108,403.1,107.8,402.9,107.6,402.3,106.9,401.4,106.2,395.4,100.8,386.2,96.1,360.1,82.9,323.3,82.9,286.4,82.9,260.4,96.1,234.3,109.3,234.3,128.1,234.3,146.8,260.4,160.1,286.4,173.3,323.3,173.3,360.1,173.3,386.2,160.1,412.3,146.8,412.3,128.1,412.3,119.6,406.9,112.2,406.6,111.7,406.2,111.2,406,111,405.8,110.7]}},47,cjs.Ease.linear).wait(1).to({x:403.3,y:108},0).to({guide:{path:[403.3,108,403.1,107.8,402.9,107.6,402.3,106.9,401.4,106.2,395.4,100.8,386.2,96.1,360.1,82.9,323.3,82.9,286.4,82.9,260.4,96.1,234.3,109.3,234.3,128.1,234.3,146.8,260.4,160.1,286.4,173.3,323.3,173.3,360.1,173.3,386.2,160.1,412.3,146.8,412.3,128.1,412.3,119.6,406.9,112.2,406.6,111.7,406.2,111.2,406,111,405.8,110.7]}},47,cjs.Ease.linear).wait(1).to({x:403.3,y:108},0).to({guide:{path:[403.3,108,403.1,107.8,402.9,107.6,402.3,106.9,401.4,106.2,395.4,100.8,386.2,96.1,360.1,82.9,323.3,82.9,286.4,82.9,260.4,96.1,234.3,109.3,234.3,128.1,234.3,146.8,260.4,160.1,286.4,173.3,323.3,173.3,360.1,173.3,386.2,160.1,412.3,146.8,412.3,128.1,412.3,119.6,406.9,112.2,406.6,111.7,406.2,111.2,406,111,405.8,110.7]}},47,cjs.Ease.linear).wait(1));

	// satellite
	this.instance_1 = new lib.juno();
	this.instance_1.parent = this;
	this.instance_1.setTransform(404.2,94.4,0.134,0.134);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({x:399.7,y:91.1},0).wait(1).to({x:394.9,y:88.1},0).wait(1).to({x:389.7,y:85.2},0).wait(1).to({x:384.1,y:82.4},0).wait(1).to({x:378.3,y:80},0).wait(1).to({x:372.2,y:77.9},0).wait(1).to({x:366,y:76},0).wait(1).to({x:359.7,y:74.5},0).wait(1).to({x:353.4,y:73.2},0).wait(1).to({x:346.6,y:72.2},0).wait(1).to({x:339.8,y:71.4},0).wait(1).to({x:332.9,y:71},0).wait(1).to({x:326.1,y:70.7},0).wait(1).to({x:319.4},0).wait(1).to({x:313.2,y:70.9},0).wait(1).to({x:307.2,y:71.3},0).wait(1).to({x:301.1,y:71.9},0).wait(1).to({x:295.1,y:72.7},0).wait(1).to({x:289,y:73.7},0).wait(1).to({x:283,y:74.9},0).wait(1).to({x:277,y:76.4},0).wait(1).to({x:271.1,y:78.1},0).wait(1).to({x:265.3,y:80.1},0).wait(1).to({x:259.6,y:82.3},0).wait(1).to({x:254.1,y:84.7},0).wait(1).to({x:248.8,y:87.3},0).wait(1).to({x:243.7,y:90.1},0).wait(1).to({x:239.4,y:92.7},0).wait(1).to({x:235.8,y:95.1},0).wait(1).to({x:232.2,y:97.7},0).wait(1).to({x:228.9,y:100.5},0).wait(1).to({x:225.7,y:103.4},0).wait(1).to({x:222.7,y:106.4},0).wait(1).to({x:220,y:109.6},0).wait(1).to({x:217.5,y:113},0).wait(1).to({x:215.4,y:116.5},0).wait(1).to({x:213.6,y:120.1},0).wait(1).to({x:212.2,y:123.7},0).wait(1).to({x:211.2,y:127.3},0).wait(1).to({x:210.5,y:130.9},0).wait(1).to({x:210.1,y:134.2},0).wait(1).to({x:210,y:137.4},0).wait(1).to({x:210.1,y:140.4},0).wait(1).to({x:210.4,y:143.3},0).wait(1).to({x:211,y:146},0).wait(1).to({x:211.7,y:148.7},0).wait(1).to({x:212.6,y:151.2},0).wait(1).to({x:213.6,y:153.7},0).wait(1).to({x:214.9,y:156.1},0).wait(1).to({x:216.2,y:158.3},0).wait(1).to({x:217.7,y:160.5},0).wait(1).to({x:219.3,y:162.5},0).wait(1).to({x:220.9,y:164.5},0).wait(1).to({x:222.6,y:166.3},0).wait(1).to({x:224.5,y:168.1},0).wait(1).to({x:226.3,y:169.8},0).wait(1).to({x:228.3,y:171.5},0).wait(1).to({x:230.3,y:173.1},0).wait(1).to({x:232.4,y:174.6},0).wait(1).to({x:234.6,y:176.1},0).wait(1).to({x:236.9,y:177.6},0).wait(1).to({x:239.3,y:179},0).wait(1).to({x:241.9,y:180.6},0).wait(1).to({x:244.8,y:182.1},0).wait(1).to({x:247.9,y:183.6},0).wait(1).to({x:251.1,y:185.1},0).wait(1).to({x:254.5,y:186.5},0).wait(1).to({x:258.2,y:187.9},0).wait(1).to({x:262,y:189.3},0).wait(1).to({x:266.1,y:190.5},0).wait(1).to({x:270.4,y:191.7},0).wait(1).to({x:274.9,y:192.7},0).wait(1).to({x:279.6,y:193.7},0).wait(1).to({x:284.5,y:194.5},0).wait(1).to({x:289.6,y:195.1},0).wait(1).to({x:295,y:195.7},0).wait(1).to({x:300.5,y:196.1},0).wait(1).to({x:306.3,y:196.3},0).wait(1).to({x:312.2},0).wait(1).to({x:318.2,y:196.2},0).wait(1).to({x:324,y:196},0).wait(1).to({x:330.1,y:195.5},0).wait(1).to({x:336.5,y:194.7},0).wait(1).to({x:343.3,y:193.7},0).wait(1).to({x:350.4,y:192.3},0).wait(1).to({x:357.8,y:190.4},0).wait(1).to({x:365.4,y:188.1},0).wait(1).to({x:373.4,y:185.2},0).wait(1).to({x:381.5,y:181.5},0).wait(1).to({x:389.8,y:177.2},0).wait(1).to({x:397.5,y:172.4},0).wait(1).to({x:403.9,y:167.6},0).wait(1).to({x:410.5,y:161.5},0).wait(1).to({x:416.3,y:154.2},0).wait(1).to({x:420.7,y:146.2},0).wait(1).to({x:423.3,y:137.6},0).wait(1).to({x:424,y:129},0).wait(1).to({x:423.1,y:120.8},0).wait(1).to({x:420.5,y:112.8},0).wait(1).to({x:416.4,y:105.4},0).wait(1).to({x:411.2,y:99},0).wait(1).to({x:405.6,y:93.7},0).wait(1).to({x:399.8,y:89.3},0).wait(1).to({x:393.1,y:85},0).wait(1).to({x:385.9,y:81},0).wait(1).to({x:378.4,y:77.5},0).wait(1).to({x:371,y:74.6},0).wait(1).to({x:363.6,y:72.2},0).wait(1).to({x:356.2,y:70.2},0).wait(1).to({x:349.1,y:68.6},0).wait(1).to({x:342,y:67.3},0).wait(1).to({x:335.1,y:66.3},0).wait(1).to({x:328.4,y:65.5},0).wait(1).to({x:321.8,y:65},0).wait(1).to({x:315.4,y:64.6},0).wait(1).to({x:309,y:64.4},0).wait(1).to({x:302.9,y:64.3},0).wait(1).to({x:296.9,y:64.4},0).wait(1).to({x:291.1,y:64.6},0).wait(1).to({x:285.4,y:65},0).wait(1).to({x:279.7,y:65.6},0).wait(1).to({x:274.1,y:66.4},0).wait(1).to({x:268.4,y:67.4},0).wait(1).to({x:262.7,y:68.5},0).wait(1).to({x:257.1,y:69.9},0).wait(1).to({x:251.5,y:71.4},0).wait(1).to({x:245.9,y:73.1},0).wait(1).to({x:240.5,y:75.1},0).wait(1).to({x:235.1,y:77.2},0).wait(1).to({x:229.7,y:79.5},0).wait(1).to({x:224.5,y:81.9},0).wait(1).to({x:219.3,y:84.6},0).wait(1).to({x:214.3,y:87.4},0).wait(1).to({x:209.4,y:90.3},0).wait(1).to({x:204.6,y:93.3},0).wait(1).to({x:199.9,y:96.5},0).wait(1).to({x:195.4,y:99.8},0).wait(1).to({x:190.9,y:103.2},0).wait(1).to({x:186.6,y:106.7},0).wait(1).to({x:182.5,y:110.3},0).wait(1).to({x:178.4,y:113.9},0).wait(1).to({x:174.6,y:117.5},0).wait(1).to({x:171.1,y:121},0).wait(1).to({x:167.6,y:124.5},0).wait(1).to({x:164.2,y:128.2},0).wait(1).to({x:160.9,y:132},0).wait(1).to({x:157.6,y:135.9},0).wait(1).to({x:154.5,y:139.9},0).wait(1).to({x:151.4,y:144},0).wait(1).to({x:148.5,y:148.2},0).wait(1).to({x:145.6,y:152.5},0).wait(1).to({x:142.8,y:156.9},0).wait(1).to({x:140.2,y:161.4},0).wait(1).to({x:137.7,y:166},0).wait(1).to({x:135.3,y:170.7},0).wait(1).to({x:133.1,y:175.5},0).wait(1).to({x:130.9,y:180.3},0).wait(1).to({x:129,y:185.3},0).wait(1).to({x:127.2,y:190.3},0).wait(1).to({x:125.5,y:195.3},0).wait(1).to({x:124,y:200.4},0).wait(1).to({x:122.6,y:205.6},0).wait(1).to({x:121.4,y:210.7},0).wait(1).to({x:120.4,y:215.9},0).wait(1).to({x:119.5,y:221.1},0).wait(1).to({x:118.7,y:226.4},0).wait(1).to({x:118.1,y:231.6},0).wait(1).to({x:117.6,y:236.7},0).wait(1).to({x:117.4,y:241.2},0).wait(1).to({x:117.3,y:245.9},0).wait(1).to({x:117.5,y:250.6},0).wait(1).to({x:117.8,y:255.5},0).wait(1).to({x:118.3,y:260.4},0).wait(1).to({x:119.1,y:265.3},0).wait(1).to({x:120.1,y:270.4},0).wait(1).to({x:121.5,y:275.5},0).wait(1).to({x:123.1,y:280.5},0).wait(1).to({x:125.1,y:285.6},0).wait(1).to({x:127.4,y:290.7},0).wait(1).to({x:130,y:295.7},0).wait(1).to({x:132.9,y:300.5},0).wait(1).to({x:136.2,y:305.2},0).wait(1).to({x:139.7,y:309.8},0).wait(1).to({x:143.5,y:314.2},0).wait(1).to({x:147.5,y:318.3},0).wait(1).to({x:151.7,y:322.3},0).wait(1).to({x:156,y:326},0).wait(1).to({x:160.5,y:329.6},0).wait(1).to({x:165.1,y:332.9},0).wait(1).to({x:169.7,y:336},0).wait(1).to({x:174.5,y:339},0).wait(1));

	// sun
	this.instance_2 = new lib.sun();
	this.instance_2.parent = this;
	this.instance_2.setTransform(321.9,128,1.784,1.784,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(192));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(578.9,282.6,111.4,63.6);
// library properties:
lib.properties = {
	id: 'A2E4DE06359349FE80EF8923076A7B4F',
	width: 550,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A2E4DE06359349FE80EF8923076A7B4F'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


// Virtual camera API : 

var VirtualCamera = new function() {
var _camera = new Object();
function ___Camera___(timeline) {
this.timeline = timeline;
this.camera = timeline.___camera___instance;
this.centerX = lib.properties.width / 2;
this.centerY = lib.properties.height / 2;
if(timeline.___camera___instance == null || timeline.___camera___instance == undefined )
{
	timeline.___camera___instance = new cjs.MovieClip();
	timeline.___camera___instance.visible = false;
	timeline.___camera___instance.parent = timeline;
	timeline.___camera___instance.setTransform(this.centerX, this.centerY);
}
this.camera = timeline.___camera___instance;
}

___Camera___.prototype.moveBy = function(x, y, z=0) {
var loc = this.getPosition();
this.setPosition(loc.x + x, loc.y + y, loc.z + z);

};
___Camera___.prototype.setPosition = function(x, y, z=0) {
this.camera.x = this.centerX - x;
this.camera.y = this.centerY - y;
};

___Camera___.prototype.getPosition = function() {
var loc = new Object();
loc['x'] = this.centerX - this.camera.x;
loc['y'] = this.centerY - this.camera.y;
loc['z'] = 0;
return loc;
};

___Camera___.prototype.resetPosition = function() {
this.setPosition(0, 0);
};

___Camera___.prototype.zoomBy = function(zoom) {
this.setZoom( (this.getZoom() * zoom) / 100);
};

___Camera___.prototype.setZoom = function(zoom) {
this.camera.scaleX = 100 / zoom;
this.camera.scaleY = 100 / zoom;
};

___Camera___.prototype.getZoom = function() {
return 100 / this.camera.scaleX;
};

___Camera___.prototype.resetZoom = function() {
this.setZoom(100);
};

___Camera___.prototype.rotateBy = function(angle) {
this.setRotation( this.getRotation() + angle );
};

___Camera___.prototype.setRotation = function(angle) {
this.camera.rotation = -angle;
};

___Camera___.prototype.getRotation = function() {
return -this.camera.rotation;
};

___Camera___.prototype.resetRotation = function() {
this.setRotation(0);
};

___Camera___.prototype.attachToObject = function(obj, deltaX=0, deltaY=0) {
this.camera.attachedToObject = obj;
this.camera.attachedToObject.attachmentOffsetX = deltaX;
this.camera.attachedToObject.attachmentOffsetY = deltaY;
};

___Camera___.prototype.changeAttachmentOffset = function(deltaX, deltaY) {
if(this.camera.attachedToObject != undefined) {
this.camera.attachedToObject.attachmentOffsetX = deltaX;
this.camera.attachedToObject.attachmentOffsetY = deltaY;
}
};

___Camera___.prototype.removeAttachment = function() {
this.camera.attachedToObject = undefined;
};

this.getCamera = function(timeline) {
if(_camera[timeline] == undefined)
_camera[timeline] = new ___Camera___(timeline);
return _camera[timeline];
}

this.getCameraAsMovieClip = function(timeline) {
return this.getCamera(timeline).camera;
}
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;